services:
  now-db-frontend:
    container_name: nowdb-frontend
    image: node:20-alpine3.16
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 5173:5173
    command: >
        sh -c "cd /usr/src/app && npm ci && npm run dev -- --host"
  now-db-backend:
    container_name: nowdb-backend
    image: node:20-alpine3.16
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 4000:4000
    command: >
        sh -c "cd /usr/src/app && npm ci && npm run dev"
  now-db:
    container_name: nowdb-db
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_HOST: localhost
      MARIADB_DATABASE: now_test
      MARIADB_LOG_DATABASE: now_log_test.log
      MARIADB_USER: now_test
      MARIADB_PASSWORD: mariadb_password
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
volumes:
  nowdb-db:

