services:
  now-db-frontend:
    container_name: nowdb-frontend
    build:
      context: frontend/
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 5173:5173
  now-db-backend:
    container_name: nowdb-backend
    image: node:20-alpine3.16
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 4000:4000
    command: >
        sh -c "cd /usr/src/app && npm ci && npx tsc && npm run start"
