services:
  now-db-frontend:
    container_name: nowdb-frontend
    build:
      context: frontend/
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 5173:5173
    environment:
      - BACKEND_URL=http://localhost:4000
  now-db-backend:
    container_name: nowdb-backend
    image: node:20-alpine3.16
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 4000:4000
    command: >
        sh -c "cd /usr/src/app && npm ci && npx tsc && npm run start"
  now-db:
    container_name: nowdb-db
    image: mariadb
    env_file: .db.dev.env
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:3306:3306
volumes:
  nowdb-db:
