services:
  now-db-frontend:
    container_name: nowdb-frontend
    image: node:20-alpine3.16
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 5173:5173
    command: >
        sh -c "cd /usr/src/app && npm ci && npm run build && npm start -- --host"
  now-db-backend:
    container_name: nowdb-backend
    image: node:20-alpine3.16
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 4000:4000
    command: >
        sh -c "cd /usr/src/app && npm ci && npx tsc && npm run start"
